export const AUTHOR_TOUCHED = 'AUTHOR_TOUCHED';
export const AUTHOR_VALID = 'AUTHOR_VALID';

export const AUTHOR_INVALID = 'AUTHOR_INVALID';
export const AUTHOR_UPDATED = 'AUTHOR_UPDATED';

export const SAVE_AUTHOR_SUCCESS = 'SAVE_AUTHOR_SUCCESS';
export const SAVING_AUTHOR = 'SAVING_AUTHOR';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
